### ISSUE TITLE
PHP versions

### ISSUE THREAD

**Issue by usagi** [melpon/wandbox#115]
現行より旧いバージョンとして 5.4, 5.3, 5.2 あたりまであるとPHPer的には嬉しいです。対応可能なようでしたらお願いします。優先度・低。

**Comment by fetus-hina** [comment]
個人的需要から https://wandbox.fetus.jp/ を立ち上げましたのでよろしければどうぞ。
PHP 5.4.16 が CentOS 7 のパッケージ、それ以外は自前ビルドです。
（しばらくは調整とかで動作が怪しいかも）

**Comment by melpon** [comment]
PHP はひなさんとこに任せるということで、Closeします。
