### ISSUE TITLE
Set CORS header "Access-Control-Allow-Origin" for REST API

### ISSUE THREAD

**Issue by BorisSchaeling** [melpon/wandbox#125]
It would be great if the HTTP responses received from the REST API would set this CORS header: 

```
Access-Control-Allow-Origin: *
```

Then one could access Wandbox with JavaScript and the XMLHttpRequest object from the browser.

**Comment by melpon** [comment]
It's a great idea! I added the header to REST API responses.

**Comment by BorisSchaeling** [comment]
Thanks, that was fast! I can confirm that it works. :)
