### ISSUE TITLE
REST API /compile.json: "application/json" is the only acceptable content type?

### ISSUE THREAD

**Issue by BorisSchaeling** [melpon/wandbox#126]
The documentation of the REST API /compile.json says:

> This API accepts "application/json" in a "Content-Type" header.

Can you confirm that "application/json" is actually the only acceptable content type? Any other encoding like "application/x-www-form-urlencoded" won't work?

**Comment by melpon** [comment]
Yes, /compile.json accepts only "application/json". (However, Wandbox source code do not check the content type for the moment.)
Because, "application/x-www-form-urlencoded" does not have types, such as a bool type in the /compile.json "save" parameter.

**Comment by BorisSchaeling** [comment]
Thanks for the clarification!
