### ISSUE TITLE
clang翻訳結果の色付き出力対応

### ISSUE THREAD

**Issue by usagi** [melpon/wandbox#127]
コンパイラーが色付き出力に対応している場合には、wandboxで見える出力も色付き対応にできないか。

**Comment by melpon** [comment]
memo: https://github.com/drudru/ansi_up

**Comment by melpon** [comment]
@kikairoya clangで標準出力にエスケープシーケンスを付けてもらうためには、以下の条件を満たす状態にしてやる必要があるらしい。( [このへん](https://github.com/llvm-mirror/llvm/blob/master/lib/Support/Unix/Process.inc)参照 )

- `isatty(STDOUT_FILENO)`が1を返す（ttyが存在する）
- `setupterm((char*)nullptr, STDOUT_FILENO, &errret)`が0を返す（セットアップに成功する）
- `tigetnum(const_cast<char*>("color"))`が0より大きい値を返す（"color"の機能が存在する）

なので、`openpty`で仮想端末作って`tcsetattr`あたりで設定すれば動きそうな感じがするんですが合ってます？

**Comment by kikairoya** [comment]
termcapはどこから設定させようか

**Comment by fetus-hina** [comment]
LLVM の出力に対応するには bold 対応が必要そう？

* https://github.com/llvm-mirror/llvm/blob/a983427f67e227649ca3da4cd8f81cc41a56e155/lib/Support/Unix/Process.inc#L418
* https://github.com/llvm-mirror/llvm/blob/f30ac8f5ece0c90d804cd6ddec142ac05e1d32f1/lib/Support/raw_ostream.cpp#L661

**Comment by fetus-hina** [comment]
（for PHP 側の操作の関係でなんかログが汚れてすみません…）

**Comment by kikairoya** [comment]
gccが\e[Kを吐くのでそれをどうにかしないといけない

**Comment by fetus-hina** [comment]
「カーソル位置から行末までをクリア」？
どうするのこれ…

**Comment by fetus-hina** [comment]
https://github.com/melpon/wandbox/issues/127#issuecomment-100432149 の bold 対応については bright として実装されていて問題なさげ
https://github.com/drudru/ansi_up/blob/8d120f8cd02ff6a83249dc0140c72c747454e322/ansi_up.js#L113
（たとえば `ESC [ 1;31` は CSI + 1 + 31 で「高輝度 or 太字」+「文字色赤」の意味らしい）

Note: http://nanno.dip.jp/softlib/man/rlogin/ctrlcode.html#CSI

**Comment by fetus-hina** [comment]
とりあえず `ESC [ 数値 K` (数字はoptional) は右側を消す場合は華麗にスルー、それ以外は改行扱いするとなんとなくは何とかなるのかしら。
あとは位置指定系のやつは改行に変換あたり？

**Comment by fetus-hina** [comment]
ansi_up へ PR 投げて、「知らないエスケープシーケンス(CSIに限る)」を含んだ時の挙動が修正された 1.2.0 がリリースされた( https://github.com/drudru/ansi_up/releases )ので #146 を更新済み。
`<ESC>[K` は CSI なので「単に無視する」挙動ならこれで行えるはず。

italic とか underline とかに無駄に対応するのは https://github.com/fetus-hina/ansi_up/blob/2bedb13c8c3263214cbb964eb8dfb3031992bec0/ansi_up.js#L107 でやっていたけどこれはこれで微妙。（ #149 との兼ね合いもあって）

**Comment by melpon** [comment]
いろいろ考慮した結果、ANSIエスケープコードには対応する、ただし仮想端末は作らない、という方針にしました。
Clang には強制的に色を付けるオプションがあるので、それを付けることでお茶を濁すことにしました。
https://github.com/melpon/wandbox/commit/44999aff222997539473c83c7092b8f09730266c

**Comment by usagi** [comment]
melponほか関係各位のご対応に感謝。
このチケットを立てた目的は翻訳に伴うwarning, error 発生時の視認性の向上なので十分に満足です。

![image](https://cloud.githubusercontent.com/assets/115972/10068640/e7b7babc-62e0-11e5-9182-abdafafb3d86.png)
