### ISSUE TITLE
C++14の数値リテラルの桁区切りにエディターの色付けを対応する

### ISSUE THREAD

**Issue by usagi** [melpon/wandbox#128]
`'`を含む数値リテラルに対してエディターの色付けが未対応で'を恐らく単文字の始まりと認識して色付けしてしまっている。翻訳とその結果への実害は無いが、やや残念なので修正されると嬉しい。

```cpp
#include <iostream>

auto main() -> int
{
  using namespace std;
  
  cout << 0b11111111'11111111 << endl;
  cout << 0xff'ff << endl;
}
```

![0038](https://cloud.githubusercontent.com/assets/115972/6429369/1555711e-c00f-11e4-8c8c-59278930e717.png)

http://melpon.org/wandbox/permlink/Xie2ybXMDdrphzD4

**Comment by melpon** [comment]
https://github.com/codemirror/CodeMirror/pull/3540

**Comment by usagi** [comment]
:+1:
