### ISSUE TITLE
実行ログローテート

### ISSUE THREAD

**Issue by melpon** [melpon/wandbox#135]
- ディレクトリ開きっぱ
- cronでディレクトリ名変更とシグナル送る
- シグナルでディレクトリ開き直し

**Comment by kikairoya** [comment]
冷静に考えたらシグナルとか必要なかった (ディレクトリ名変えられた時に出力先ディレクトリ掘りなおすだけでよかった)

**Comment by kikairoya** [comment]
@melpon cronかなにかで


> #!/bin/sh
> cd /var/log/wandbox
> s=\`date +%Y%m%d`
> mv ran wandbox_ran.$s
> tar caf wandbox_ran.$s.tar.xz --backup=t -- wandbox_ran.$s


をするとバックアップとれるはず。ローテートがほしければ要相談

**Comment by melpon** [comment]
これって、複数ファイルに対応した時、ループ中にディレクトリの名前変更された場合に半端に書かれることになりません？
