### ISSUE TITLE
ウェブサーバのルートに配置しようとするとHTMLのリンクが少なくとも1箇所壊れる

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#140]
`http://example.com/` で wandbox を動かすことを考えたときに、

kennel2 の `map_root` を `"/"` にすると、
`<script src="//static/js/jquery.url.js"></script>`
のようなHTMLが生成されて `static` がホスト名になります。
（`http://static/js/jquery.url.js` を探しに行きます）

一方、 `map_root` を `""` にすると、
`<a class="navbar-brand" href="">Wandbox</a>`
のようなHTMLが生成されて、左上 "Wandbox" 部分からのリンクが死にます。
（たとえばpermlinkからトップに戻れなくなります）

本家Wandbox的には問題のない箇所なので自力でなんとかするつもりですが一応issueにしておきます。

**Comment by melpon** [comment]
多分これで大丈夫（たぶん）（未確認）（人柱）（あとは任せた）

**Comment by fetus-hina** [comment]
動いたようです。ありがとうございます。
