### ISSUE TITLE
Languageをまたぐコンパイラ変更が無視されることがある

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#142]
再現手順(一例):

1. `C++` -> `gcc HEAD` を選択しておきます。
2. たとえば `C` -> `gcc 4.8.2` を選択します。これは正しく動きます。(`gcc 4.8.2` が選択されます)
3. `C++` -> `gcc HEAD` を選択します。`gcc 4.8.2` のままになります。

原因:

言語をまたぐコンパイラ切り替えをしたとき(1->2)、上の例だと `gcc HEAD` が `<li class="active">` のまま放置されます。（実装的には tab 毎に active が最大一つずつあり得るとかいう感じですかね）

後で(2->3)この「別タブの `.active` な要素」を選ぶと `shown.bs.tab` イベントが着火せず、コンパイラの変更が行われません。

**Comment by melpon** [comment]
カレントのコンパイラのインデックスと、HTML的に手前のLanguagesのコンパイラのインデックスが同じだと起きるっぽいですね。
タブ切り替えを行うグループの単位って何も考えてなかったので、その辺が怪しそう。

**Comment by melpon** [comment]
直ったはず
