### ISSUE TITLE
出力表示を行っているあたりを仮想端末とする

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#149]
関連: #127

> [@melpon] ぜひWeb仮想コンソール作って下さい -- https://twitter.com/melponn/status/596991731305811968
> [@fetus-hina] Wandboxは「出力は画面を模す」「出力されたものを垂れ流すだけであそこは画面ではない」どちらを目指すのか？ -- https://twitter.com/fetus_hina/status/596992633441898497
> [@melpon] 前者に寄せたい -- https://twitter.com/melponn/status/596993455861014529
> [@kikairoya] 出力画面から直接入力したくならないか -- https://twitter.com/kikairoya/status/597205785974743040
> [@melpon] なる -- https://twitter.com/melponn/status/597206018993426433

おそらくkennel だけではすまなくて cattleshed も巻き込んだ大改造になりそうな気配がするのでやるかどうかも含めて

**Comment by melpon** [comment]
いろいろ考慮した結果、ANSIエスケープコードには対応する、ただし仮想端末は作らない、という方針にしました。
ということでこれはcloseします。
