### ISSUE TITLE
extra optionsやstdinの入力欄で無駄に高度な技術を使わない

### ISSUE THREAD

**Issue by mikecat** [melpon/wandbox#155]
AndroidのOpera Classicにおいて、Use Legacy Editorを有効にすればソースコードの入力と実行はできますが、
extra optionsやstdinの欄ではCodeMirrorという無駄に高度な技術が使われているようで、
入力が反映されず、改行すると入力した内容が消えてしまう、ということがあります。

これらの欄ではプレーンテキストしか入力しない可能性が高そうなので、
常に or Use Legacy Editorの設定を反映し 普通のtextareaにしていただけると助かります。
ご検討よろしくお願いします。

**Comment by melpon** [comment]
Legacyモードは今後拡張する予定はありません。なので無駄に高度な技術を使い続けます。
その代わり JS, CSS 無しで動かせるモードを用意したので、うまく動かない場合はそちらを使って下さい。

http://melpon.org/wandbox/nojs
