### ISSUE TITLE
同じコンパイラが複数の言語にまたがって存在しているとき、selectのような表示の部分で区別がつきづらい

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#156]
※「selectのような表示」の部分は実際には `button`

> 気づいたけど、wandbox、gccのバージョンしか出ないから、これがCなのかCPPなのかC++なのか、一瞬わからなくなる

https://twitter.com/Flast_RO/status/610355231033942016

現状でも一応、オプションや `run-command` 表示部分で区別はつきますがなんとかした方が良さそうな気はします

が、単純に `[C++] gcc 4.8.2` みたいに表示するのも狭い領域がさらに喰われて微妙感。

**Comment by melpon** [comment]
![2015-09-20 15 12 01](https://cloud.githubusercontent.com/assets/816539/9979473/05bf42ee-5faa-11e5-994b-7a70c70bb1aa.png)
