### ISSUE TITLE
-fsanitize=undefined for Clang

### ISSUE THREAD

**Issue by AaronBallman** [melpon/wandbox#157]
It seems that -fsanitize=undefined does not work when compiling with Clang due to link errors, but does work with GCC.

**Comment by melpon** [comment]
You can use `-fsanitize=undefined` with Clang HEAD now.

**Comment by melpon** [comment]
I will close on 2015-06-29(+09:00) if no comment.

**Comment by AaronBallman** [comment]
Sorry for the delayed response; I can confirm ubsan now works with Clang HEAD. Thank you!

**Comment by melpon** [comment]
:+1:
