### ISSUE TITLE
Getting Internal Server Error when trying to post code to API

### ISSUE THREAD

**Issue by ned14** [melpon/wandbox#158]
Can you see anything wrong with this? If I manually copy and paste the 220Kb single include file into the wandbox UI, it all works fine. Before I script up code to pretend to be a human pressing buttons on your web UI, maybe there is something obvious below which is causing the internal server error?

Thanks,
Niall
```
ned@jenkins64:~/boost.afio$ ./send_to_wandbox.sh
+ json_wandbox send_to_wandbox.cpp afio_single_include.hpp
+ echo -e -n '{ "code" : '
+ json_escape send_to_wandbox.cpp
+ cat send_to_wandbox.cpp
+ python -c 'import json,sys,codecs; sys.stdout.write(json.dumps(codecs.getreader("ISO-8859-1")(sys.stdin).read()))'
+ echo -e -n ',
      "codes": [
          { "file": "afio_single_include.hpp", "code": '
+ json_escape afio_single_include.hpp
+ cat afio_single_include.hpp
+ python -c 'import json,sys,codecs; sys.stdout.write(json.dumps(codecs.getreader("ISO-8859-1")(sys.stdin).read()))'
+ echo -e '}],
      "options": "warning,boost-1.58,c++14",
      "compiler": "clang-head",
      "save": true
    }'
+ curl -v -F json_file=@json_input.json http://melpon.org/wandbox/api/compile.json
* Hostname was NOT found in DNS cache
*   Trying 49.212.130.73...
* Connected to melpon.org (49.212.130.73) port 80 (#0)
> POST /wandbox/api/compile.json HTTP/1.1
> User-Agent: curl/7.35.0
> Host: melpon.org
> Accept: */*
> Content-Length: 243073
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------c58a2396982a31f8
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
* Server nginx/1.9.0 is not blacklisted
< Server: nginx/1.9.0
< Date: Thu, 18 Jun 2015 23:56:48 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 500 Internal Server Error
< X-Powered-By: CppCMS/1.0.4
* HTTP error before end of send, stop sending
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>500 &mdash; Internal Server Error</title>
  </head>
  <body>
    <h1>500 &mdash; Internal Server Error</h1>
  </body>
</html>
* Closing connection 0
+ [[ '' != '' ]]
+ echo

ned@jenkins64:~/boost.afio$
```

**Comment by melpon** [comment]
Wandbox API accepts only that Content-Type is "application/json".

```
$ curl -v -H "Content-type: application/json" -d @json_input.json http://melpon.org/wandbox/api/compile.json
```

(Please change a `save` flag to `false` while you don't need.)

**Comment by ned14** [comment]
Same problem:

```
ned@jenkins64:~/boost.afio$ ./send_to_wandbox.sh
+ json_wandbox send_to_wandbox.cpp afio_single_include.hpp
+ echo -e -n '{ "code" : '
+ json_escape send_to_wandbox.cpp
+ cat send_to_wandbox.cpp
+ python -c 'import json,sys,codecs; sys.stdout.write(json.dumps(codecs.getreader("ISO-8859-1")(sys.stdin).read()))'
+ echo -e -n ',
      "codes": [
          { "file": "afio_single_include.hpp", "code": '
+ json_escape afio_single_include.hpp
+ cat afio_single_include.hpp
+ python -c 'import json,sys,codecs; sys.stdout.write(json.dumps(codecs.getreader("ISO-8859-1")(sys.stdin).read()))'
+ echo -e '}],
      "options": "warning,boost-1.58,c++14",
      "compiler": "clang-head",
      "save": true
    }'
+ curl -v -H 'Content-type: application/json' -F json_file=@json_input.json http://melpon.org/wandbox/api/compile.json
* Hostname was NOT found in DNS cache
*   Trying 49.212.130.73...
* Connected to melpon.org (49.212.130.73) port 80 (#0)
> POST /wandbox/api/compile.json HTTP/1.1
> User-Agent: curl/7.35.0
> Host: melpon.org
> Accept: */*
> Content-Length: 243073
> Expect: 100-continue
> Content-type: application/json; boundary=------------------------f19f7efe3e0c942e
>
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
* Server nginx/1.9.0 is not blacklisted
< Server: nginx/1.9.0
< Date: Fri, 19 Jun 2015 01:37:09 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 500 Internal Server Error
< X-Powered-By: CppCMS/1.0.4
* HTTP error before end of send, stop sending
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>500 &mdash; Internal Server Error</title>
  </head>
  <body>
    <h1>500 &mdash; Internal Server Error</h1>
  </body>
</html>
* Closing connection 0
+ [[ '' != '' ]]
+ echo

ned@jenkins64:~/boost.afio$
```

Regarding changing save flag to false, this script is intended for Boost libraries to automatically create playpens of themselves per-commit for integration into their github and docs, and eventually, the main Boost website so interested users can launch a playpen of a Boost library just like they can with Rust libraries. So, if that's going to be a big load for you, do say so, we can look into other online web compilers.

**Comment by ned14** [comment]
Actually, a member of the Boost community supplied me with a python wandbox uploader script which just works. That solves my problem, so sorry about the noise. Do get back to me if you're worried about load, wandbox is shortly to appear in https://svn.boost.org/trac/boost/wiki/BestPracticeHandbook#a14.USERFRIENDLINESS:Considerlettingpotentialuserstryyourlibrarywithasinglemouseclick whereupon I would assume your server load will substantially rise.

**Comment by melpon** [comment]
In order to send JSON data, use `-d` or `--data` with curl.
`-F` flag encode to multipart/form-data.

About save flag, I'm worried increase DB size not load.
However, to save about 10-20 tiimes a day is no problem.

**Comment by ned14** [comment]
An idea about the save flag: If one could supply a fixed 256 bit number for every API push in the JSON, then your DB could spot when the number is the same as an existing entry and delete the previous entries (or better, reuse the permalink). Each project would then choose their own fixed 256 bit number to tag all their pushes. This might make your DB size much easier to manage.

How long do permalinks last before getting garbage collected? Would a curl fetch on a weekly cronjob be enough, or would daily be better?

BTW regarding DB bloat, my very small Boost library consumes 1.1Mb being pushed to wandbox every commit. Other Boost libraries push past 10Mb, some 30Mb. That's a lot of data for you. If you had a method of accepting bzip2 compressed data you can reduce that 10x in bandwidth costs, even with gzip it's 6x reduction.

**Comment by kyawoonay** [comment]
Not bad
