### ISSUE TITLE
API の OPTIONS ハンドリング

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#162]
https://ja.wikipedia.org/wiki/XMLHttpRequest
> POST などで、text/plain など以外の Content-Type をクロスドメインで送信する場合、OPTIONS を使いプレフライトが行われる

OPTIONS で 405 になって死ぬという悲しい状態になるようなので対応しておいた方がよさげ。
気が向いたらやります。

**Comment by melpon** [comment]
たぶんできたはず
