### ISSUE TITLE
C++>=11とboost.signals2などの組み合わせで`std::auto_ptr`の警告がでないようにできないか

### ISSUE THREAD

**Issue by usagi** [melpon/wandbox#166]
方向現時点、wandboxでC++11, C++14 などのモードと boost.signals2 などの組み合わせで以下の警告、

```
warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
```

が相当数発生してなかなか心の臓と結果の可読性に良くない。

再現リンク: http://melpon.org/wandbox/permlink/0mp6GqDgVreDIISk

C++03、C++11、C++14それぞれのモードで使用されるboostライブラリーを切り替えるなどで、うまく対応できないだろうか。

**Comment by usagi** [comment]
b2でC++14とかモード設定してもこれは出るようなのでwandbox側の対応ではない、という事に気付いたので取り下げクローズします。お騒がせしました :rabbit:

**Comment by Flast** [comment]
それはBoostに報告すべき内容と思います（と書いているうちにcloseされた

で、Boost.Coreについては https://github.com/boostorg/core/pull/13 これで、Boost.SmartPtrに関しては一度[develop ML](http://lists.boost.org/Archives/boost/2015/07/224310.php)に流れましたが、そのまま流れました

小手先のWAとしては、 [`-Wno-deprecated-declarations`](http://melpon.org/wandbox/permlink/CKVuHDVuENTIBybL) を渡してしまうのが簡単だと思います

先のCoreに関してはBoost 1.59で有効なります
[SmartPtrに関して](http://melpon.org/wandbox/permlink/uzUHYSewSP7Po02l)は[`-DBOOST_NO_AUTO_PTR`](http://melpon.org/wandbox/permlink/CQzGDD8sIRSs3VdM)で黙ります

**Comment by usagi** [comment]
@Flast nice supplement :+1:

**Comment by Flast** [comment]
ついき

Boost.SmartPtrについても対応が入りました https://github.com/boostorg/smart_ptr/commit/df904965833dcf1bf2eb4d7d1416369dd806e092

**Comment by usagi** [comment]
@Flast :+1:
