### ISSUE TITLE
VIM mode for editor

### ISSUE THREAD

**Issue by matwey** [melpon/wandbox#167]
Hello,

Could you please add VIM emulation mode for code editor? I mean, implement commands like dd,% etc.

**Comment by melpon** [comment]
![2015-08-27 10 48 50](https://cloud.githubusercontent.com/assets/816539/9510724/1ce195ac-4caa-11e5-9114-8c715c22da16.png)

(but, % is not provided.)
I'm using [CodeMirror](https://codemirror.net/) for these key bindings.

**Comment by fetus-hina** [comment]
You can use `%` now. (by #168, but its PR is written in Japanese.)

UI is not perfect now. Popup window will appear when you type `:` or `/`.
I (or project member) will try update the UI. It will be like [CodeMirror official example](https://codemirror.net/demo/vim.html).

The search/replace popup window will works perfectly. There is no reason to avoid the use of Vim emulation mode.

@matwey 
This issue will close when that UI update applied. Have you any question?

@melpon 
I'll try that update in few days.

**Comment by matwey** [comment]
Many thanks for your help!
