### ISSUE TITLE
Vimモードのノーマルモード中に:や/を押したときにポップアップが出る

### ISSUE THREAD

**Issue by fetus-hina** [melpon/wandbox#169]
#167 #168
[公式サンプル](https://codemirror.net/demo/vim.html)が本物のVimっぽい挙動をするので、同じようにすればVimらしくなるはず。
ただし、Expandオプションと組み合わせると使い物にならない可能性があります。
作ってみてから考えます。

数日中に試してみます。

**Comment by melpon** [comment]
いい感じにいけてたので追加しときました。
`:w` すると CodeMirror.commands.save が呼ばれるっぽいのですが、保存するかコンパイルするか、ひとまずエラーが出ないようにしてしまうか悩み中

**Comment by fetus-hina** [comment]
Expand と組み合わせた時の挙動も思ったより良いですねこれ

**Comment by fetus-hina** [comment]
`:w` は compile まではしてあげるのが良いような気がしますが、C++ + 複数タブの時、タブ切り替えにいくつもりで、「いつもの癖」で `:w` とか叩いちゃうと大惨事ですかねえ…。

**Comment by melpon** [comment]
まあこのままでいいやってことでclose。
