### ISSUE TITLE
Please add python 3.4 / 3.5

### ISSUE THREAD

**Issue by ismail** [melpon/wandbox#170]
Also it would make sense to remove now unsupported python 3.3.2.

**Comment by melpon** [comment]
Added.
Python 3.4.3: http://melpon.org/wandbox/permlink/ZzwvjlkeOI9hLncI
Python 3.5.0: http://melpon.org/wandbox/permlink/CEAp07tKgKxAXhjK

**Comment by ismail** [comment]
Thanks a lot!
