### ISSUE TITLE
dmd compiler for D

### ISSUE THREAD

**Issue by markisaa** [melpon/wandbox#175]
I was gonna try and toss up a pull request for this but I can't see how to make it happen. In any case, the dmd compiler is the standard/reference compiler for D. The gdc compiler lags behind in its development cycle and for that reason is less useful. Could definitely see myself using wandbox if it had proper D support :).

**Comment by melpon** [comment]
I added dmd compiler now.
http://melpon.org/wandbox/permlink/9sHmCxv2tZ0lHwAQ

**Comment by melpon** [comment]
Wandbox compilers managed by [chef](https://github.com/melpon/chef-melpon.org).
But, We will change managing method soon so do not accepts pull requests now.

**Comment by markisaa** [comment]
@melpon - Wow! I thought the odds of getting this added so soon were.... close to zero. Many thanks! I think I have a new favorite place to test code snippets! Gonna go tell all the folks over at dlang.org :)
