### ISSUE TITLE
Remove Rust 1.0 and add rust 1.7 stable and 1.8 beta?

### ISSUE THREAD

**Issue by ismail** [melpon/wandbox#177]
Rust 1.0 is seriously outdated. Would be nice to remove it and make room for 1.7 stable and 1.8 beta.

**Comment by melpon** [comment]
I add Rust 1.7.0 but I don't add 1.8.0.
1.8.0 is beta. When 1.8.0 is stable, I will install it (if remember).
And 1.0.0 is not removed for permanent codes.

**Comment by ismail** [comment]
Thanks a lot!
