### ISSUE TITLE
c++11 and higher have std::atomic that need -latomic

### ISSUE THREAD

**Issue by ajneu** [melpon/wandbox#178]
Hi,

Please link with 
```bash
-latomic
```

so that the following code will compile:
http://melpon.org/wandbox/permlink/9AageJz9nvjb90jE

```cpp
#include <atomic>
#include <array>
#include <iostream>

int main()
{
    std::atomic<std::array<char,100>> str(std::array<char,100>{"asdf"});
    auto s = str.load();
    std::cout << s.data() << std::endl;
}
```

Thanks for wandbox. It's superuseful to quickly switch between different compilers!!!
(Any plans of including gcc 5.3 which was released December 4, 2015 ([ref](https://gcc.gnu.org/gcc-5/)) ?)

**Comment by ajneu** [comment]
Ah, a possible workaround is to use the "extra options" field:
http://melpon.org/wandbox/permlink/gswgOtFqJXlZux0e

**Comment by melpon** [comment]
That is right to use "extra options". If there is much demand `-latomic`, I will add checkbox it.
(I'd forgotten to install gcc 5.3. I will install later.)

**Comment by ajneu** [comment]
Ok great! Thanks.
