### ISSUE TITLE
Haskell - ghc HEAD 8.1 error in malloc on the simplest test case

### ISSUE THREAD

**Issue by spaghetti-** [melpon/wandbox#181]
http://melpon.org/wandbox/permlink/tk3kpfSpsYWdKrK5

Works fine on 7.10 http://melpon.org/wandbox/permlink/EUV60TpzckIIr4TT

```hs
main :: IO ()
main = do
    return ()
```

Error:
```
Start
malloc: failed on request for 72 bytes; message: newInCall
254
Finish
```

**Comment by melpon** [comment]
fixed. ghc-head requires more address space than other ghc versions.
