### ISSUE TITLE
boost::system::error_code::message() の挙動が怪しい

### ISSUE THREAD

**Issue by redboltz** [melpon/wandbox#184]
``` cpp
#include <iostream>
#include <boost/system/system_error.hpp>

int main() {
    boost::system::error_code ec;
    std::cout << ec.value() << std::endl;
    std::cout << ec.message() << std::endl;
}
```

上記コードにて、ec.message()のところで、g++だと落ち、
http://melpon.org/wandbox/permlink/wdkeaMlseIzrpyZR
clang++だと化ける。
http://melpon.org/wandbox/permlink/EJIpUNbBpoEt7EmG

ローカル環境でテストしたところ、正しく`Success`と表示され、valgrindでチェックしても特にエラーは報告されなかった。

**Comment by melpon** [comment]
`BOOST_ERROR_CODE_HEADER_ONLY` を定義したり、gcc-4.8.2 だと動くことから、多分 Boost をビルドしているコンパイラのバージョンと実行しているコンパイラのバージョンが一致してないことによる問題だと思います。
（確か Wandbox で提供している Boost をビルドしている gcc のバージョンは 4.8 系）

いつか直さないとなーと思いつつ放置している部分なので、早く直したいところ cc: @kikairoya

**Comment by melpon** [comment]
修正しました: http://melpon.org/wandbox/permlink/OJu0Aj9yGr8eM9OH
