### ISSUE TITLE
How to pass command line arguments to the built app?

### ISSUE THREAD

**Issue by adishavit** [melpon/wandbox#185]
I can't seem to find how to pass command line arguments to the built app?  
Is there a way to do this?

**Comment by melpon** [comment]
Use bash. http://melpon.org/wandbox/permlink/CF9mxfWYH4yHxQe6

Alternatively, if you are using [API](https://github.com/melpon/wandbox/blob/master/kennel2/API.rst), you can specify _runtime-option-raw_.

**Comment by adishavit** [comment]
Actually I was wondering how to do it on the web site.

**Comment by melpon** [comment]
To avoid complex UI, Wandbox on the web is hiding the textbox.

**Comment by adishavit** [comment]
Can't a single line editbox be added just above the stdin edit box?
I wanted to live demonstrate a command line parsing library but I cannot do this without having the option to pass such arguments!

**Comment by melpon** [comment]
Implemented.
However, runtime arguments is rarely used.
So it is hard to see.
<img width="588" alt="2016-09-15 1 44 07" src="https://cloud.githubusercontent.com/assets/816539/18521230/3d0da08a-7ae6-11e6-84f3-9a10252fe131.png">

**Comment by adishavit** [comment]
I see it now!
But ut seems that all the params are passed in as a single argument:

**Comment by melpon** [comment]
The arguments are spited by line break. http://melpon.org/wandbox/permlink/D28bAnVd9rnU5ES2
(It is design error, but can not change for compatibility)

**Comment by adishavit** [comment]
I am not an expert, but looking at the commit, it seems that the underlying code requires the line break - that you should not change.  
However, you could make the UI have only a single like edit-box and use JS to split on spaces and construct the line-break representation desired by the command processor. 
This would also take case of arguments with leading and trailing spaces which cannot happen in real command lines since the shell strips these as well.

**Comment by melpon** [comment]
It is not impossible, but...
- Old permanent-link arguments will be invalidated, so rewrite their saved data.
- Wandbox has JSON API. So I should implement splitting command line arguments on C++.
- Splitting command line arguments such as a shell is difficult. (Quote a string includes spaces, tabs and line-break, escaping characters, processing punctuation characters `();<>|&` and a comment character `#`, and more...)

**Comment by adishavit** [comment]
1. How many old links are there? Didn't you just add this feature in the last commit?
2. well... maybe just the web interface is a first step?
3. True. I didn't mean a full-fledged shell parse. Just split on spaces (and trim them)

**Comment by melpon** [comment]
1. All permanent-links are alive, 20,000 over. I didn't commit this feature. see below.
2. I can.
3. I need to include spaces in an argument, so I want to implement quote. but It needs a many time.

About the 1,

Compile-time and Run-time arguments is saved to Wandbox database (using SQLite).
The arguments is string that is input on UI and including line-break on now implementation.
On the new UI, The arguments form will be changed to not include line-break and split on spaces.
On the new UI, Wandbox should process old form arguments and new form arguments.
It needs a many time, so I thought I convert old form arguments to new form arguments in advance. (that is, _rewrite their saved data_)

**Comment by adishavit** [comment]
I see. Well, I hope you do get around to doing this when you have the time.
Thanks for the great site!
