### ISSUE TITLE
[feature request] spirit_x3サポート

### ISSUE THREAD

**Issue by redboltz** [melpon/wandbox#186]
https://github.com/djowel/spirit_x3/tree/master/include をincludeパスに加えて欲しいです。問題なければ。
次期バージョンのspiritでヘッダオンリーライブラリです。

**Comment by melpon** [comment]
問題ないですが、いくつか質問です。
- masterブランチは毎日pullした方がいいですか？
- Boostライブラリと併用した時に、Boost.Spiritとspirit_x3はどっちが優先された方がいいですか？
- gccやclangの全てのバージョンにパスを加えたほうがいいですか？

なおUI上では特にチェックボックスは用意せず、暗黙にincludeパスを追加する予定です。
（そのうちBoostにマージされると思われるので）

**Comment by redboltz** [comment]
> * masterブランチは毎日pullした方がいいですか？

はい。ここ最近後進されてませんが。。。バグ修正など合ったときには対応したいので。

> * Boostライブラリと併用した時に、Boost.Spiritとspirit_x3はどっちが優先された方がいいですか？

spirit_x3です。ただ、チェックボックス無しで、spirit_x3を優先すると、何かしらの不整合が発生する可能性があるかも知れないので、チェックボックス対応の方が良いのではないかな？という気はします。ディレクトリ構成とかファイル名とかはぶつかっているみたいですし、https://github.com/djowel/spirit_x3/tree/move_to_boost というブランチもありますし何らかの整合措置がとられているのかな？と推測。（ただし、こちらは、masterよりいろいろbehindみたいなのでmasterの方が良いです）

> * gccやclangの全てのバージョンにパスを加えたほうがいいですか？

C++14サポート前提(generic lambdaを利用する)ため、そのサポートがあるバージョン～でないと使えないと思いますが、全部に加えてもいいんじゃないかなと。

**Comment by melpon** [comment]
> チェックボックス対応の方が良いのではないかな？
これをすると、Boostにマージされた時にチェックボックスが不要になるので削除したいのですが、そうするとspirit_x3を使ったpermlinkを開いた時にどう見せるかが難しくなるかなぁと思ってます。
古いBoostのために、マージ後もチェックボックスは常に残しておきましょうかね…。

> C++14サポート前提(generic lambdaを利用する)ため、そのサポートがあるバージョン～でないと使えないと思いますが、全部に加えてもいいんじゃないかなと。
どうせ個別に指定していくので、C++14以降のオプションがあるバージョンだけにしておきます。

**Comment by redboltz** [comment]
> 古いBoostのために、マージ後もチェックボックスは常に残しておきましょうかね…。

これで良いんじゃないかな？と思います。

**Comment by melpon** [comment]
追加しました。が、 https://github.com/djowel/spirit_x3/blob/master/example/x3/calc1.cpp を試してみるとコンパイルエラーが起きて動かない状態です。
http://melpon.org/wandbox/permlink/saDXZehis9n2EClj

**Comment by redboltz** [comment]
こちらでも確認しました。
エラーを元に、いろいろ調べたところ、衝撃の事実が判明しました。
spirit x3は、既にboostにマージされており、spirit x3へのcommitも本家（boost）の方が進んでいるようです。

現在のboostにもspirit x3のexampleが存在し、
https://github.com/boostorg/spirit/blob/develop/example/x3/calc/calc1.cpp
http://melpon.org/wandbox/permlink/5VJFNpBQgq38MyVj
で、コンパイルは通りました。

gccは実行時にエラーとなっているっぽいですがclangではうまく動きました。

https://github.com/boostorg/spirit/blob/develop/example/x3/calc/calc6.cpp
http://melpon.org/wandbox/permlink/5onkMts0Mz3PRp9T

calc6.cppでは計算結果も出ています。

まだマージされていないと思い込んでいたため、https://github.com/djowel/spirit_x3/tree/master/include が最新だとばかり。

よって、boostがinclude pathに含まれていれば、最新のspirit x3が使えるということになります。
つまり本issueの対応は不要であると。
私の確認不足で、不要な対応に時間を割いていただいてしまい申し訳ありません。

**Comment by melpon** [comment]
お、了解です。じゃあrevertします。

**Comment by redboltz** [comment]
ではcloseします。

**Comment by Flast** [comment]
確かにSpirit X3はすでにリリースに含まれていますが、X3のXはeXperimentalなのでproductionで使うことはおすすめしませんとだけ補足しときます
