### ISSUE TITLE
[feature request] boost experimental sml (msm-lite)のサポート

### ISSUE THREAD

**Issue by redboltz** [melpon/wandbox#187]
https://github.com/boost-experimental/sml
をサポートしていただけるとありがたいです。

* daily update 必要
* g++ clang++ C++14をサポートしているバージョン
* header only library
* include/boost という構成だが、トップに sml.hpp とあとはsml/ にあるので、常時インクルードパスに入っていても害はなさそう。

**Comment by melpon** [comment]
だん: http://melpon.org/wandbox/permlink/m3Ei8w4pfP7QGa64

https://github.com/melpon/wandbox/commit/52d8439c9a5f5278dfd332387efae298f7609ae0

**Comment by redboltz** [comment]
http://melpon.org/wandbox/permlink/xf0OTM3qKenElrlx
確認しました。ありがとうございます！
