### ISSUE TITLE
numpyをサポートしてほしい

### ISSUE THREAD

**Issue by lv7777** [melpon/wandbox#189]
pythonの代表的なライブラリであるnumpyをサポートしてほしいのですがお願いできないでしょうか？

**Comment by melpon** [comment]
追加しました。 http://melpon.org/wandbox/permlink/SomVYwWnUPklsbTZ

**Comment by lv7777** [comment]
ありがとうございます！！！助かりました！

**Comment by escape173** [comment]
numpy が使えないのは僕の環境だけでしょうか？
https://wandbox.org/permlink/Bc2TnQe6n8I2cocx
サポートを取り消されたのでしたら、またサポートしていただけると幸いです。
