### ISSUE TITLE
Clang trunk is broken -- libc++ should use libc++abi not libsupc++

### ISSUE THREAD

**Issue by EricWF** [melpon/wandbox#190]
Currently [Clang trunk fails to link any program](http://melpon.org/wandbox/permlink/huML5LuicFK1RDet) because `libc++.so` is missing symbols.

This is caused because `libc++.so` is built using an old libsupc++/libstdc++ to provide the ABI library bits. I think it would be better to use `libc++abi.so` instead, since that is the default libc++ configuration.

Here are the [docs for building libc++](http://libcxx.llvm.org/docs/BuildingLibcxx.html#id3).
If you need any help please let me know (I maintain libc++).

Additionally thank you for your service. wandbox is great and I use it daily.

**Comment by EricWF** [comment]
I see the Clang ToT option has been removed. Can we expect it back soon?

**Comment by melpon** [comment]
I probably fixed.

**Comment by EricWF** [comment]
LGTM! Thanks again. Did you switch to libc++abi?

**Comment by EricWF** [comment]
> Did you switch to libc++abi?

After a little investigating the answer is Yes! Closing this bug as fixed.
