### ISSUE TITLE
Boost incompatibility with newer gcc versions (5.x and up).

### ISSUE THREAD

**Issue by takacsd** [melpon/wandbox#191]
If you use some boost library which is not header only, you can get errors because gcc changed its string implementation to make it c++11 conform in gcc 5.x.

So the following simple code:
```cpp
#include <sstream>
#include <iostream>

#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/text_iarchive.hpp>


int main() {
    std::stringstream ss;
    
    {
        boost::archive::text_oarchive oa(ss);
        oa << 23;
    }
    
    std::cout << ss.str() << std::endl;
    
    return 0;
}
```
compiles with gcc 4.9 but not with gcc 5.1.
(It does not work at all with any of the clang versions...)

**Comment by melpon** [comment]
fix: http://melpon.org/wandbox/permlink/zCVnwi0yi8M9RLl0
