### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by dbigham** [melpon/wandbox#193]
Thanks so much for providing Wandbox!  Have you considered setting up a second server and only giving it access to people who pay $10/mo? (or something like that)  I'm finding that simple Java compiles take around 5 seconds, which is OK, but I'd love it if runtimes could be < 2 seconds :)

**Comment by dbigham** [comment]
I suppose there are existing sites like ideone that are probably (?) fast and I should just pay them if I need the speed. (and they support lots of different languages)

**Comment by melpon** [comment]
Wandbox is slow now. Because, a server compile HEAD compilers is same as Wandbox runtime server.
HEAD compilers is compiled every day for over 12 hours.

I'm working to resolve.
I'm going to separate the server to HEAD compiling server and Wandbox runtime server.
