### ISSUE TITLE
GCC and Clang not updating

### ISSUE THREAD

**Issue by EricWF** [melpon/wandbox#197]
Previously it seemed that GCC and Clang trunk versions were updated every night. However it now appears that they haven't updated since Dec 19th.  Is this intended? Should these still be updating nightly?

**Comment by melpon** [comment]
It is intended. Daily building is stopped now.
Daily building is heavy, and the server is same as Wandbox runtime server.
So, Wandbox is very slow while the server build compilers.

However gcc and clang is used by many users.
I put back only gcc and clang daily building.
the compilers will be updated within one day.

I'm trying separate building and runtimer server.
If it is completed, all daily building will be returned.

**Comment by EricWF** [comment]
> However gcc and clang is used by many users.
> I put back only gcc and clang daily building.

Awesome! Thank you!

I work with a bunch of GCC and Clang developers and we really appreciate melpon.org having daily builds. It allows us to send compile results to other developers which may not have the newest compilers.

**Comment by EricWF** [comment]
Closing since this has since been fixed.
