### ISSUE TITLE
crash for sanitizer flag with gcc

### ISSUE THREAD

**Issue by cppchedy** [melpon/wandbox#198]
Hi,
I want to report that I get a crash when I use gcc flag -fsanitize with the following output:
- ASan
```
==20==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
==20==ReserveShadowMemoryRange failed while trying to map 0xdfff0001000 bytes. Perhaps you're using ulimit -v
```
- TSan

```
FATAL: ThreadSanitizer CHECK failed: ../../../../source/libsanitizer/sanitizer_common/sanitizer_allocator_primary64.h:74 "((kSpaceBeg)) == ((reinterpret_cast<uptr>( MmapFixedNoAccess(kSpaceBeg, TotalSpaceSize))))" (0x7b0000000000, 0xfffffffffffffff4)

Segmentation fault
```

for the address sanitizer I think it's a limit in the provided Virtual memory, but I am not sure.
I have no idea for thread sanitizer.

any suggestions?

**Comment by melpon** [comment]
Unfortunately, Wandbox can't support AddressSanitizer.

Wandbox runtime is limited address space by `prlimit --as=...`.
AddressSanitizer do not work on limited environment.

https://clang.llvm.org/docs/AddressSanitizer.html#limitations:

> On 64-bit platforms AddressSanitizer maps (but not reserves) 16+ Terabytes of virtual address space. This means that tools like ulimit may not work as usually expected.

**Comment by cppchedy** [comment]
that's unfortunate. and for ThreadSanitizer?

**Comment by melpon** [comment]
ThreadSanitizer has [same limitation](https://clang.llvm.org/docs/ThreadSanitizer.html#limitations):

> ThreadSanitizer maps (but does not reserve) a lot of virtual address space. This means that tools like ulimit may not work as usually expected.
