### ISSUE TITLE
Clang Trunk should use -stdlib=libc++ to add libc++ includes

### ISSUE THREAD

**Issue by EricWF** [melpon/wandbox#199]
Currently the configuration for clang-trunk is forced to use the libc++ headers using "-nostdinc++ -I/opt/wandbox/clang-head/include/c++/v1". This makes it impossible to use clang-trunk with libstdc++.

I believe the Clang trunk configuration should use the "-stdlib=libc++" flag to force the use of libc++ (Clang should automatically find the correct headers). Also the implicit "-stdlib=libc++" should be inserted *before* user provided options so that it can be overridden using "-stdlib=libstdc++".

I'm happy to contribute these changes if you tell me where to find the configuration files used by http://melpon.org/wandbox/ (They don't appear to be in this repo)

**Comment by melpon** [comment]
There is the configuration in [here](https://github.com/melpon/wandbox-builder/blob/master/cattleshed-conf/compilers.py).
Clang 3.3 or later on Wandbox is using [`-stdlib=libc++`, `-nostdinc++`](https://github.com/melpon/wandbox-builder/blob/131fe028ae8342eb385fa4ddea8e71645b5fa540/cattleshed-conf/compilers.py#L654).

User specified options (`-O2`, `-Wall`, Boost libraries, etc) are located after `compile_command`.

**Comment by EricWF** [comment]
The `-nostdinc++` part cannot be overridden, and causes clang-trunk to always bind to libc++. Using `-stdlib=libc++` should be enough since Clang will search for the libc++ headers along it's own installation prefix first.

**Comment by EricWF** [comment]
closing this issue. I'll file a PR against wandbox-builder. Thank you.
