### ISSUE TITLE
Internal server error when uploading headers

### ISSUE THREAD

**Issue by badair** [melpon/wandbox#200]
About 10 minutes ago, I failed to upload headers to Wandbox via http://melpon.org/wandbox/api/compile.json . This seems to be a regression bug. The last time I used this successfully was several months ago.

**Comment by melpon** [comment]
Thank you for reporting!
I did not notice the bug. Wandbox is terminated every several tens of minutes.
For the reason of CppCMS is updated 1.0.4 to 1.0.5.
