### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by dbigham** [melpon/wandbox#201]
Recently whenever I try to use the Wandbox API I get HTTP response code 500.

**Comment by melpon** [comment]
What your tested code?
It seems to work.

```
$ cat test.json
{
  "code":"#include <iostream>\nint main() { std::cout << \"hello\" << std::endl; }",
  "compiler": "gcc-head"
}
$ curl -H "Content-type: application/json" -d "`cat test.json`"  http://melpon.org/wandbox/api/compile.json
{
	"program_message" :	"hello\n",
	"program_output" :	"hello\n",
	"status" :	"0"
}
```

**Comment by dbigham** [comment]
```
{
  "code":"class MyClass { public static void main(String[] args) { System.out.println(\"Hello, world!\"); } }",
  "options": "",
  "compiler": "java8-openjdk",
  "compiler-option-raw": ""
} 
```

**Comment by melpon** [comment]
`"java8-openjdk"` is already removed.
Please use `"openjdk-jdk8u121-b13"` instead of `"java8-openjdk"`.

```json
{
  "code": "class prog { public static void main(String[] args) { System.out.println(\"Hello, world!\"); } }",
  "compiler": "openjdk-jdk8u121-b13"
}
```

Enable compiler names are listed by [`/list.json`](https://github.com/melpon/wandbox/blob/master/kennel2/API.rst#get-listjson)

**Comment by dbigham** [comment]
This is problematic because if I hard code "openjdk-jdk8u121-b13" into my sources, then it will break when you change the version.  How can I configure my code to use JDK 8 in a way that won't break when you update the Java 8 version?

**Comment by melpon** [comment]
No solution.
I don't breaking changes as possible, but I can't ensure.
If you noticed, list compiler names and change the code.

**Comment by dbigham** [comment]
Why not have something named "OpenJDK 8 HEAD" like you do for other things with "HEAD" as part of the name?

**Comment by melpon** [comment]
"HEAD" is conventionally named to a compiler that is built every day.
However, OpenJDK 8 is not built every day, and is provided only "jdk8u121-b13" now.
I keep this version as possible, however, for example, future OS on Wandbox run-time server may not support OpneJDK 8. So I can't ensure to provide the version in the future.

**Comment by melpon** [comment]
Probably, the version "jdk8u121-b13" can be used about 2 years.
