### ISSUE TITLE
Page doesn't load when platform.twitter.com is unresponsive

### ISSUE THREAD

**Issue by Quuxplusone** [melpon/wandbox#202]
Possibly related to the current AWS outage, I'm observing that http://melpon.org/wandbox/ doesn't load (it just hangs forever).
The HTTP request that it's waiting on is a GET of http://platform.twitter.com/widgets.js , i.e., this line: https://github.com/melpon/wandbox/blob/84dcce441138f2e83927a161aba306f9e20e7186/kennel2/src/root.tmpl#L68

It would be very nice if the page would still load even when platform.twitter.com is down. I'm not sure of the details, but I imagine that basically you could load the page and then make the request to Twitter in the background, populating the Twitter-dependent widgets only once the response was received.

**Comment by fetus-hina** [comment]
@melpon 
Quick fix way: Replace it to: `<script src="//platform.twitter.com/widgets.js" async></script>`

**Comment by melpon** [comment]
@Quuxplusone fixed. Thank you for reporting.
@fetus-hina Thank you for your advice.
