### ISSUE TITLE
Support for `-E` (print preprocessed output)

### ISSUE THREAD

**Issue by Quuxplusone** [melpon/wandbox#203]
You might think that `gcc -E` would be supported out of the box already, because Wandbox normally shows the output of the compiler. But it doesn't work.
```
Start
execve: Permission denied
1
Finish
```
I think the problem is that `gcc my-input-file.c -E -o temporary-file.exe` writes the preprocessed output into `temporary-file.exe` (as if you'd redirected standard output to that file); and then Wandbox tries to `execve` that non-executable file, and of course that fails.

A simple solution could be: "if the output file is non-executable, `cat` it instead of executing it".

**Comment by melpon** [comment]
Yes, `gcc -E` doen't work.
For such purpose, Wandbox provide CPP (C Preprocessor): http://melpon.org/wandbox/permlink/OR6Lx72X1nAeUAii
Please use it.
