### ISSUE TITLE
Boost.DI (experimental) を include pathに入れて欲しい

### ISSUE THREAD

**Issue by redboltz** [melpon/wandbox#205]
https://github.com/boost-experimental/di
ヘッダオンリーライブラリです。
デフォルトブランチの cpp14 をデイリー update で入れていただけるとありがたいです。

よろしくお願いいたします。

**Comment by melpon** [comment]
done: http://melpon.org/wandbox/permlink/8zSYpwPtnIWA5Kaz

**Comment by redboltz** [comment]
ありがとうございました！！
