### ISSUE TITLE
perlのtemplateのコメントが正しくないので修正してほしい

### ISSUE THREAD

**Issue by Fuyutsubaki** [melpon/wandbox#208]
perlのコメント行は `# ` なので `//` であると構文エラーになってしまう
実行結果：https://wandbox.org/permlink/qfRnDMUHzqcRjBfE

https://github.com/melpon/wandbox-builder/blob/7f006a17a65056f5aee0886a796bd50ab4bc4e7c/cattleshed-conf/templates/perl/prog.pl#L1

**Comment by melpon** [comment]
ありがとうございます。修正しました。
