### ISSUE TITLE
Custom compiler options get double-quoted then rejected by GCC

### ISSUE THREAD

**Issue by koalization** [melpon/wandbox#210]
Hi, I have this particular issue everytime I want to feed my own options to GCC in the Compiler options textbox. The options are supplied to the compiler in double quotes, and GCC won't recognize them.
![screenshot_2017-05-05_21-07-04](https://cloud.githubusercontent.com/assets/26254032/25760483/3945ffbc-31d7-11e7-9527-7786a9bd41fd.png)

**Comment by melpon** [comment]
The arguments are split by line break. https://wandbox.org/permlink/FyaiXJDHKbeUaBEO
(I think it is design error, but can not change it for compatibility)
