### ISSUE TITLE
RapidSSL certs are going to be distrusted

### ISSUE THREAD

**Issue by saki7** [melpon/wandbox#218]
> The SSL certificate used to load resources from https://wandbox.org will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

![fasdasdsaf](https://user-images.githubusercontent.com/1901813/32124639-79210798-bba3-11e7-8cd7-7c19097dba83.png)

https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

**Comment by melpon** [comment]
Fixed by introducing JPRS SSL.

**Comment by saki7** [comment]
Confirmed. Thanks!
