### ISSUE TITLE
Need help with post query to compiler

### ISSUE THREAD

**Issue by DDaemonium** [melpon/wandbox#224]
I'd like to use your online compiler in my project, but I can't sent post request to compiler.
My code sample:
`$.ajax({
	type: "POST",
	url: "hhttp://melpon.org/wandbox/api/compile.json",
	data:{
	compiler: "gcc-head",
	code:"// This file is a \"Hello, world!\" in C++ language by GCC for wandbox.↵#include <iostream>↵#include <cstdlib>↵#include <fstream>↵↵int main()↵{↵    std::ofstream out(\"o.txt\");↵    std::ifstream in(\"o.txt\");↵    out << 2;↵    int h = 0;↵    in >> h;↵    std::cout << h << std::endl;↵}↵↵// GCC reference:↵//   https://gcc.gnu.org/↵↵// C++ language references:↵//   https://msdn.microsoft.com/library/3bstk3k5.aspx↵//   http://www.cplusplus.com/↵//   https://isocpp.org/↵//   http://www.open-std.org/jtc1/sc22/wg21/↵↵// Boost libraries references:↵//   http://www.boost.org/doc/↵",
	codes:[{file: "noname-1", code: "////↵////"}],
	compiler:"gcc-head",
	compiler_option_raw:"",
	options:"warning,boost-1.66.0-gcc-head,gnu++2a,cpp-no-pedantic",
	runtime_option_raw:"",
	stdin:"123 654"
	},
	success: suc, 
	dataType: "application/json"
});`
But I get error 
`Failed to load hhttp://melpon.org/wandbox/api/compile.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by melpon** [comment]
Replace `hhttp` to `http`

**Comment by DDaemonium** [comment]
Thanks, but now I have new access error
`Failed to load http://melpon.org/wandbox/api/compile.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 500.`

**Comment by melpon** [comment]
Replace `http://melpon.org/wandbox` to `https://wandbox.org`.

**Comment by DDaemonium** [comment]
Change URL on `https://wandbox.org/api/compile.json` . But get same error. `Failed to load https://wandbox.org/api/compile.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://daemonium.96.lt' is therefore not allowed access. The response had HTTP status code 500.` I try connect from localhost and free hosting.

**Comment by fetus-hina** [comment]
@DDaemonium, could you try with this update?

```
$.ajax({
  type: "POST",
  url: "hhttp://melpon.org/wandbox/api/compile.json",
  contentType: "application/json", // <- ADD THIS
  data: JSON.stringify({compiler: "gcc-head", code: "...", ... }), // <- CHANGE THIS
  compiler:"gcc-head",
  ...
});
```

@melpon, it looks this issue is not a cross-origin problem.
It looks the client sends parameter with `Content-Type: application/x-www-form-urlencoded`.
Then, Kennel or CppCMS gives up with `bad_cast` like this:
```
Feb  5 20:40:15 goya kennel: 2018-02-05 20:40:15; cppcms, error: Caught exception [cppcms::json::bad_cast:  error converting from undefined]
Feb  5 20:40:15 goya kennel: 0x48502e: ??? + 0x48502e in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x48617d: ??? + 0x48617d in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x42ace1: ??? + 0x42ace1 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x42c19f: ??? + 0x42c19f in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x413d60: ??? + 0x413d60 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x4636d6: ??? + 0x4636d6 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x4608eb: ??? + 0x4608eb in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x4123d5: ??? + 0x4123d5 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x460671: ??? + 0x460671 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x4608eb: ??? + 0x4608eb in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x4123d5: ??? + 0x4123d5 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x454d59: ??? + 0x454d59 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x456264: ??? + 0x456264 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x457bf6: ??? + 0x457bf6 in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x501b0a: ??? + 0x501b0a in /opt/wandbox/wandbox/bin/kennel
Feb  5 20:40:15 goya kennel: 0x7f0dc4954e25: ??? + 0xc4954e25 in /lib64/libpthread.so.0
Feb  5 20:40:15 goya kennel: 0x7f0dc354a34d: clone + 0x6d in /lib64/libc.so.6
Feb  5 20:40:15 goya kennel: (http_context.cpp:139)
```

**Comment by DDaemonium** [comment]
@fetus-hina Thanks! It's work! 
I'm creating service for interactive learning. This online compiler will help in creating programming lessons. I've no team, so if u interested in it, write me linkoln3636@yandex.ru. I'm glad any help.
