### ISSUE TITLE
F# を追加してほしいです

### ISSUE THREAD

**Issue by cannorin** [melpon/wandbox#226]
F# 4.1 をサポートしているオンラインコンパイラが現状存在しないので、もし追加していただければとても嬉しいです。

コンパイル手順は http://fsharp.org/use/linux/ に記載されています。

何卒よろしくお願いします。

**Comment by melpon** [comment]
4.1 以外にはどのバージョンが欲しいですか？
4.1.34 は追加しますが、それ以外を https://github.com/fsharp/fsharp/releases あたりから選んで貰えると。

**Comment by cannorin** [comment]
https://github.com/fsharp/fsharp/releases/tag/3.1.1.26

https://github.com/fsharp/fsharp/releases/tag/4.0.0.4

https://github.com/fsharp/fsharp/releases/tag/4.1.25

と 4.1.34 でお願いします。

**Comment by melpon** [comment]
了解です。4.1.25 と 4.0.0.4 は多分ビルドできると思います。
3.1.1.26 は、ちょっと古いのでビルドできるかどうか分からないですが、試してみます。ダメだったら諦める方向で…。

**Comment by cannorin** [comment]
かなり前のバージョンなのでダメだったら抜いていただいて大丈夫です！

**Comment by melpon** [comment]
Wandbox に F# を追加しました: https://wandbox.org/permlink/1f7GNvjJ0L8jiXYN
F# HEAD はデイリーでビルドされます。
何か問題があれば教えて下さい。

**Comment by cannorin** [comment]
ありがとうございました🙏
