### ISSUE TITLE
PHP環境のデフォルトタイムゾーンを設定して欲しい

### ISSUE THREAD

**Issue by chinsoft-ando** [melpon/wandbox#227]
PHPのデフォルトタイムゾーンが設定されていないので、時間を扱うときに一々  date_default_timezone_setを呼ばなきゃいけなくて、タイプ量がたくさん増えて大変なので、Asia/TokyoでもUTCでもどこでもいいので、デフォルトタイムゾーンを設定して欲しい

**Comment by melpon** [comment]
修正しました。

**Comment by chinsoft-ando** [comment]
確認したのでクローズします
