### ISSUE TITLE
Need some help to install 

### ISSUE THREAD

**Issue by rockieloser** [melpon/wandbox#229]
Hi, i'm trying to install Wandbox.
i didn't change anything, and ran:
>open start
>connect start 
and get stuck.

then i saw kennel2's README. 
:There are kennel settings (root, port, domain, etc) in kennel.json.in. You can rewrite this file before run ./configure.
so i rewrote (change domain and host)
`    , "domain": "wandbox.org"
    , "map_root": ""
    , "dispatch_root": ""
    , "cattleshed":
        [{ "host" : "153.121.40.132"
         , "port" : 2012
}]`
to 
`    , "domain": "127.0.0.1"
    , "map_root": ""
    , "dispatch_root": ""
    , "cattleshed":
        [{ "host" : "127.0.0.1"
         , "port" : 2012
}]`
and ran:

>open start
>connect start 
>connction established from 127.0.0.1:57902
>semaphore create
>connected
>building compiler list
>run [bin/sh, -c ,/usr/local/mono-2.6.7/bin/mcs --version | head -1| cut -d'' -f5]
>finished
>semaphore destroy
>finish
>cppcms::crypto::key Failed to open file:/path/to/file/.session.key

Is it legal to rewrite ?
or how should i do ?

i need some help to build this.
Thank you

**Comment by melpon** [comment]
Generate a session key file by yourself.
The key at least 32 hexadecimal digits key length. For example `a0c92075c0dbf3b8acbc5f96ce3f0ad2`.
ref: http://cppcms.com/wikipp/en/page/cppcms_1x_config#session.client.key_file

**Comment by rockieloser** [comment]
okay. I can access to the web.
Thanks!
If i have more questions,i will ask here.

**Comment by melpon** [comment]
Open `<cattleshed_installed_directory>/etc/cattleshed.conf` and remove the directory from `--mount` option on all `"jail"` settings and then restart cattleshed.

**Comment by rockieloser** [comment]
ok . it can compile. Thank you a lot!

**Comment by rockieloser** [comment]
`Run $PREFIX/bin/cattleshed as a user permitted to rwx to jails' working
directory and ran log directory except root.`
`DO NOT RUN CATTLESHED AS ROOT OR ALL YOUR SYSTEM WILL BELONG TO THE CRACKER.`

so I use `chmod 777 $PREFIX/bin/cattleshed and all files  installed ` , but still occurs "Permisson denied".
I only success when using `sudo $PREFIX/bin/cattleshed` .
Is it ok to use `sudo` ? or what can i change for this.

**Comment by melpon** [comment]
Open <cattleshed_installed_directory>/etc/cattleshed.conf and check `"basedir"` and `"storedir"` path in `"system"`.
This user is required to permit these paths to write.

**Comment by chang860605** [comment]
HI
I wanna try to see my logs with the database, and I found `kennel_production.sqlite`.
Then I compiled many times  on my `localhost`.
In `"storedir":"/var/log/wandbox/ran"` directory, i can see many folders and contained `prog.c`. but those are empty, and `kennel_production.sqlite` is empty,too.
the correct `prog.c` and `prog.exe` are stored in  `basedir":"/tmp/wandbox`.
Is there something i missed to do or not allow to store to  `kennel_production.sqlite` ?

Thanks you!




 .

**Comment by melpon** [comment]
It is correct behaviour. Only code and results that pressed the share button on Wandbox will be saved in `kennel_production.sqlite`.

**Comment by rockieloser** [comment]
Hi,
I want to do `load template` for compiler.
how should I do to add default code to website?
like: 

```
#include <stdio.h>
   int main()
  {
   printf("\n");
  }
```
I read `compiler.default` ,and I think I should edit `template` part,but there is no example for that.
Can you give me a example?
Thank you!

**Comment by melpon** [comment]
```json
{
  "templates": {
    "gcc-helloworld": "#include <stdio.h>\n   int main()\n  {\n   printf(\"hello\\n\");\n  }"
  },
  "compilers": [
    {
      "name": "gcc-head",
      "templates": [
        "gcc-helloworld"
      ]
    }
  ]
}
```

To generate full example, run this script:

```bash
git clone https://github.com/melpon/wandbox-builder
cd wandbox-builder/cattleshed-conf/
./update.sh

# generated at here:
cat ../wandbox/cattleshed-conf/compilers.default
```

**Comment by rockieloser** [comment]
hi, i want to  `sign in` github on  localhost.
but i got locahost/?code=xxxx.... after that,and menu bar was still white.
so i think i did something wrong. 
Is it ok to use `sign in` on localhost?
how should  `callback URL`  be? Is it as same as `Homepage URL` ?

Thanks.

**Comment by rockieloser** [comment]
Hi,I'm trying to store all codes to the database.
I find ''make_permlink'' in ''perming.h''
is the step to store code to database.
So I think I should put that after compliling.
Then I added ''post_permlink'' after ''compile'' in ''kennel.cpp'' and make_random_name(16->18)(give it another length）.
But got something wrong.
Got Exception Bad_Cast(like issue#138).
How should I edit or what missed?
Thanks a lot.
