### ISSUE TITLE
Clang HEAD with Boost 1.67 doesn't work correctly

### ISSUE THREAD

**Issue by Flast** [melpon/wandbox#230]
Compiler is not able to find any files regarding boost 1.67.
https://wandbox.org/permlink/Lm9OcD1mtlXUoUMJ

**Comment by melpon** [comment]
ref: https://github.com/boostorg/asio/pull/91/commits/a58e2343efe86f7255692c16fd610bafc70ada18

I will try to apply a patch file before build boost 1.67.

**Comment by melpon** [comment]
fixed applying the patch https://github.com/melpon/wandbox-builder/commit/b3d3423ffbfe666dd33d7d15d930b5374da7f85d#diff-d2ace22e01440944e80f243ab6667299

**Comment by Flast** [comment]
Confirmed. Thanks!
