### ISSUE TITLE
Delete permlinks

### ISSUE THREAD

**Issue by fzyukio** [melpon/wandbox#231]
The real issue is: wandbox.org's permlinks are indexed and searchable.
Example: https://www.google.co.nz/search?q=iostream+site:wandbox.org&ei=AnHdWrCpFcL58QXN7IuABw&start=40&sa=N&biw=1920&bih=1103
Should have proper `robots.txt` or `noindex`, `nofollow` tags. Permlinks are shareable but not supposed to be searchable.

Currently is there a way or API to delete a permlink?

**Comment by melpon** [comment]
> Currently is there a way or API to delete a permlink?

No way. I will erase it manually if you contact to me.

> The real issue is: wandbox.org's permlinks are indexed and searchable.

I don't know what is problematic by searchable. However, there is no advantage in searchable, so I think that it is okay to set noindex and nofollow tag.

**Comment by gopi487krishna** [comment]
Has this problem been resolved i want to delete a link that i have shared . Is it possible?
