### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [melpon/wandbox#237]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/melpon/wandbox/blob/428a912dfe16fe0a1e219bde6184f66a250c0502/kennel2/configure.ac#L74 "Update candidate")?

**Comment by melpon** [comment]
It looks good. I will study for the script.

**Comment by melpon** [comment]
CMake に移行したので AX_PTHREAD を使う必要は無くなりました。
