### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [melpon/wandbox#238]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the destructor of the class “context”](https://github.com/melpon/wandbox/blob/fc107bdfe729fc0de1d3bbcfb23ae8281c940770/kennel2/src/http_client.h#L30 "Update candidate: context destructor").

**Comment by melpon** [comment]
`curl_easy_cleanup()` and `curl_slist_free_all()` function is not `free()`

**Comment by elfring** [comment]
Does these function implementations share the same known reaction for received null pointers?

**Comment by melpon** [comment]
I don't know because it is not explicitly specified for null pointer behaviour in the these functions documentation.

**Comment by elfring** [comment]
:crystal_ball: I am curious if a corresponding clarification request will change the situation further for the usage of cURL functions (besides looking at the original source code).
