### ISSUE TITLE
scrollTopを設定する箇所がパフォーマンス上のボトルネックになっている

### ISSUE THREAD

**Issue by kazatsuyu** [melpon/wandbox#239]
Chrome 68.0.3440.84 にて、以下のコードをコンパイルしたところ、~数分間~数十秒間CPU使用率100%のままページが固まる現象が起きました。（訂正：数分間は固まっていませんでした）  
https://wandbox.org/permlink/HFa7TPvoT2kxNaXl

パフォーマンスプロファイリングをしてみたところ、以下の箇所がボトルネックになっているようです。  
https://github.com/melpon/wandbox/blob/21d643d8c9b0cbf34f897b3c63c965e010b97495/kennel2/static/js/root.js#L1134  
![image](https://user-images.githubusercontent.com/6465609/43815377-67bdfdfc-9b0a-11e8-95e3-eeac933056f4.png)

上記コードは以下のループから複数回実行され、scrollTopを指定する度にレイアウトの再計算が走るようなので、ループ中のスクロール座標指定を抑制してループ終了後にまとめて移動するようにすれば良いのではないかと思います。  
https://github.com/melpon/wandbox/blob/21d643d8c9b0cbf34f897b3c63c965e010b97495/kennel2/static/js/PostEventSource.js#L60-L81

**Comment by melpon** [comment]
報告ありがとうございます。
ループの外で更新するようにしたら大分マシな速度になりました。
まだ高速化できそうな感じではありますが、特に問題無さそうなら閉じちゃいます。

**Comment by kazatsuyu** [comment]
対応ありがとうございます。  
まだ若干固まるようですが、操作できなくなって数十秒経過みたいなことにはならなくなっているようなのでとりあえず問題ないと思います。

**Comment by melpon** [comment]
では閉じまーす
