### ISSUE TITLE
[request/suggestion] Support the R language

### ISSUE THREAD

**Issue by eddelbuettel** [melpon/wandbox#243]
wandbox looks like a magnificient service with outstanding support across compilers within a language (say, C++) as well as broad support across languages.

R is a open-source (GPL-2+ licensed) system, language and environment for "programming with data" used for statistical graphics, data visualization, modeling and estimation.  With all the interest in statistics, data science, and machine learning it has been in the top-20 in eg the [Tiobe indices](https://www.tiobe.com/tiobe-index/r/).  There have been annual (major) R releases for the last several years, before that (major) releases were biannual.  You could eg rely on [the Debian snapshots of R](http://snapshot.debian.org/package/r-base/) if you wanted to support multiple versions.  We also have Docker containers covering different versions as part of the [Rocker Project](https://www.rocker-project.org/).

I would love to see R supported on wandbox.  I have been involved with R for some time, have maintained the Debian package(s) for many years, am part of the Rocker Project, and volunteer on the board of the R Foundation. 

I would be happy to make contacts and facilitate next steps if that is of interest.   Thank you in advance for considering it.

**Comment by melpon** [comment]
Wandbox not support graphics, console only. Does R language work with console only?

**Comment by eddelbuettel** [comment]
Absolutely!  Graphics is one use case, computation is another. In either R itself, or also via foreign-language interface integrations -- I myself use R as a front-end-to C++ work we do via Rcpp; see e.g. [this recent paper / vignette](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-introduction.pdf).  We also have interfaces on the command-line -- R comes with `Rscript`; I have been involved with `r` from [littler](https://github.com/eddelbuettel/littler).

The info page for the R tag at StackOverflow has a good overview too:  https://stackoverflow.com/tags/r/info

How can I help?

**Comment by melpon** [comment]
ok. I will try to install R language.

Please tell me:

- Example R code to check if it work correctly.
- Running command with R source file.
- R versions to use.

**Comment by eddelbuettel** [comment]
You rock.  I had since been thinking over coffee how to help with that.  But we're covered -- R itself (and its by now 13,000 (!!) tested packages) do all this in batch mode.

So let's try something here with some of the built-in data sets.  Let's try something interactively:

```r
R> data(iris)      ## the "hello, world" of statistics.
R> summary(iris)   ## a simple summary of the columns
  Sepal.Length   Sepal.Width    Petal.Length   Petal.Width        Species  
 Min.   :4.30   Min.   :2.00   Min.   :1.00   Min.   :0.1   setosa    :50  
 1st Qu.:5.10   1st Qu.:2.80   1st Qu.:1.60   1st Qu.:0.3   versicolor:50  
 Median :5.80   Median :3.00   Median :4.35   Median :1.3   virginica :50  
 Mean   :5.84   Mean   :3.06   Mean   :3.76   Mean   :1.2                  
 3rd Qu.:6.40   3rd Qu.:3.30   3rd Qu.:5.10   3rd Qu.:1.8                  
 Max.   :7.90   Max.   :4.40   Max.   :6.90   Max.   :2.5                  
R> table( iris[, "Species"] )   # tabulation of the Species columns

    setosa versicolor  virginica 
        50         50         50 
R> stopifnot( as.integer(table(iris[, "Species"])) == c(50L, 50L, 50L) )
R> 
```

or in a file, say, `/tmp/simpleDemo.R`:

```r
data(iris)      ## the "hello, world" of statistics.
summary(iris)   ## a simple summary of the columns
table( iris[, "Species"] )   # tabulation of the Species columns
stopifnot( as.integer(table(iris[, "Species"])) == c(50L, 50L, 50L) )
cat("All done\n")
```

which we can run via _e.g._

```sh
edd@rob:/tmp$ Rscript simpleDemo.R 
  Sepal.Length   Sepal.Width    Petal.Length   Petal.Width        Species  
 Min.   :4.30   Min.   :2.00   Min.   :1.00   Min.   :0.1   setosa    :50  
 1st Qu.:5.10   1st Qu.:2.80   1st Qu.:1.60   1st Qu.:0.3   versicolor:50  
 Median :5.80   Median :3.00   Median :4.35   Median :1.3   virginica :50  
 Mean   :5.84   Mean   :3.06   Mean   :3.76   Mean   :1.2                  
 3rd Qu.:6.40   3rd Qu.:3.30   3rd Qu.:5.10   3rd Qu.:1.8                  
 Max.   :7.90   Max.   :4.40   Max.   :6.90   Max.   :2.5                  

    setosa versicolor  virginica 
        50         50         50 
All done
edd@rob:/tmp$ 
```

and note how `summary()` and `table()` print here.  Whereas if I use another (newer) mechanism and just evaluate the expression of sourcing the file, I get less output:

```r
edd@rob:/tmp$ R -q -e 'source("simpleDemo.R")'
R> source("simpleDemo.R")
All done
R> 
R> 
edd@rob:/tmp$ 
```

(The `-q` makes R quiet, otherwise you get the GNU GPL greetings and hints for help.)  

Lastly, if you have it, `r` can do this too but we have to a) turn on statement printing via `-p` and b) explicitly load the datasets package:

```
edd@rob:/tmp$ r -ldatasets -p simpleDemo.R
  Sepal.Length   Sepal.Width    Petal.Length   Petal.Width        Species  
 Min.   :4.30   Min.   :2.00   Min.   :1.00   Min.   :0.1   setosa    :50  
 1st Qu.:5.10   1st Qu.:2.80   1st Qu.:1.60   1st Qu.:0.3   versicolor:50  
 Median :5.80   Median :3.00   Median :4.35   Median :1.3   virginica :50  
 Mean   :5.84   Mean   :3.06   Mean   :3.76   Mean   :1.2                  
 3rd Qu.:6.40   3rd Qu.:3.30   3rd Qu.:5.10   3rd Qu.:1.8                  
 Max.   :7.90   Max.   :4.40   Max.   :6.90   Max.   :2.5                  

    setosa versicolor  virginica 
        50         50         50 
All done
edd@rob:/tmp$ 
```

If you vary the condition in the `stopifnot()` you get a failure. Think of it as a simple `assert()`:

```r
R> stopifnot( as.integer(table(iris[, "Species"])) == c(1, 2, 3) )
Error: as.integer(table(iris[, "Species"])) == c(1, 2, 3) are not all TRUE
R> 
```

That makes it easy to create counter examples etc.    Does this help?

As for versions, most of us in the R community tend to stick with current released version, so now R 3.5.1.  We often test against 'R-devel' which many of us build locally, I also update a Docker container weekly.   Similarly, one or two releases back would be nice as people sometimes hang with those.

But as a just just having R 3.5.1 (or 3.5.0 or one of the 3.4.* releases) would be awesome!

**Comment by melpon** [comment]
Thank you to help!

**Comment by melpon** [comment]
Installed to Wandbox R 3.5.1 and R devel: https://wandbox.org/permlink/WZl6mtg53FI335jv
R devel is updated daily.

**Comment by eddelbuettel** [comment]
You are awesome.  Just run `sessionInfo()` on the `r-devel`. Ubuntu LTS. Good platform.  (And just in case you didn't see this -- we do have "R-release" for you here via [this repo at CRAN](https://cloud.r-project.org/bin/linux/ubuntu/) and have various recipes for building R-devel from source.  But I reckon you learned all that already by yourself.  Impressive stuff.

I tweeted [yesterday](https://twitter.com/eddelbuettel/status/1035919548757749760) about this, folks seemed to like this already, and just sent a [follow-up tweet](https://twitter.com/eddelbuettel/status/1036223922218446848).  This should get exposure quickly _as it is a truly great service_.  Thank you.  Should I find anything to suggest in the R implementation I will surely report back.  

I am closing this issue ticket as the request was ever-so-promptly fulfilled.  Thank you.

**Comment by daroczig** [comment]
This is great, thanks a lot! I was playing a bit with the simple PHP frontend as well at https://wandbox.org/nojs/r-head, but run into err 500s by trying to run `sum(1:10)`. Can you help me understand what I'm doing wrong?

**Comment by melpon** [comment]
@daroczig It seems that it is not only problem in R language. So I created new issue #244. Thank you for your reporting.

**Comment by eddelbuettel** [comment]
Here is a slightly nicer template; what I posted above was meant more as a litmus test for you:

```r
# This file is a "Hello, world!" in R language for wandbox.

data(iris)                               ## the "hello, world" of statistics.
summary(iris)                            ## a simple summary of the columns
fit <- lm(Sepal.Length ~ . , data=iris)  ## basic regression
summary(fit)                             ## summary  

cat("All done\n")

# R language references:
#   https://cran.r-project.org/manuals.html
```

**Comment by melpon** [comment]
done.
