### ISSUE TITLE
Favicon for wandbox

### ISSUE THREAD

**Issue by nelsonjchen** [melpon/wandbox#246]
I think there was a refactor that eliminated this icon. It'll be nice if it a favicon could be added back into modern wandbox.

https://github.com/melpon/wandbox/commit/35e6447eea54001897b05078748f243697ad1446

https://raw.githubusercontent.com/melpon/wandbox/35e6447eea54001897b05078748f243697ad1446/kennel/static/favicon.ico

**Comment by melpon** [comment]
Resolved #251
