### ISSUE TITLE
About Smart Indent

### ISSUE THREAD

**Issue by busyhuman** [melpon/wandbox#252]
Hi.
I'm a student using wandbox.
I just write this to ask something about 'Smart Indent' in editor.
There are lots of tabs on next line that 'Smart Indent' is checked, but I don't remember when the error occured and why. It works fine it is not checked.
I think Something wrong with stack counting '{' and '}'.

Thank you.
[smidt.txt](https://github.com/melpon/wandbox/files/2748508/smidt.txt)

**Comment by melpon** [comment]
Wandbox is using [CodeMirror](https://codemirror.net/index.html) as an editor.
The editor provides a [smartIndent option](https://codemirror.net/doc/manual.html#option_smartIndent).
'Smart Indent' is the smartIndent option.

**Comment by busyhuman** [comment]
Sorry I'm confused
