### ISSUE TITLE
expand feature missing

### ISSUE THREAD

**Issue by matkatmusic** [melpon/wandbox#256]
Expand feature removed from editor/output panes with commit https://github.com/melpon/wandbox/commit/0396f67649a6f1e9be4f0939a0f40a4ad50dcd80.   This feature removal lowers the quality of experience by end-users.

**Comment by matkatmusic** [comment]
bump.   I find it hard to believe that folks don't miss this feature.

**Comment by melpon** [comment]
Please send PR.

**Comment by matkatmusic** [comment]
How about just undoing this commit: 
`https://github.com/melpon/wandbox/commit/0396f67649a6f1e9be4f0939a0f40a4ad50dcd80`

**Comment by matkatmusic** [comment]
BUMP

**Comment by melpon** [comment]
SEND PR.

**Comment by matkatmusic** [comment]
BUMP!!   How hard is it to undo a commit?   you made wandbox unusable if a snippet is longer than 20 lines of code.
