### ISSUE TITLE
C++ documentation link in template source leads to obsolete site

### ISSUE THREAD

**Issue by Xeverous** [melpon/wandbox#259]
The 'load template' option generates a samle program with the following content:

```cpp
#include <cstdlib>

int main()
{
    std::cout << "Hello, Wandbox!" << std::endl;
}

// Clang reference:
//   https://clang.llvm.org/

// C++ language references:
//   https://msdn.microsoft.com/library/3bstk3k5.aspx
//   http://www.cplusplus.com/
//   https://isocpp.org/
//   http://www.open-std.org/jtc1/sc22/wg21/

// Boost libraries references:
//   http://www.boost.org/doc/
```

The website `http://www.cplusplus.com/` is outdated and has been superseeded by `https://en.cppreference.com/`. I propose to change the link, cplusplus.com is not updated and does not contain as thorough language documentation as cppreference

**Comment by melpon** [comment]
Fixed
