### ISSUE TITLE
Possibly dangerous client-side vulnerability 

### ISSUE THREAD

**Issue by w1d3m0d3** [melpon/wandbox#262]
I've discovered a way to break the website in unexpected ways which might potentially result in arbitrary code execution on client machines. I would like to post more details but I'd prefer doing so in private for the sake of safety.

My naive first attempt isn't quite enough to confirm arbitrary code execution but it makes it seem dangerous enough. Best case scenario it's just a UI bug.

**Comment by melpon** [comment]
Please send mail to me from my profile.

**Comment by melpon** [comment]
Thank you for reporting! I fixed this issue.

**Comment by w1d3m0d3** [comment]
Thanks for being quick!
