### ISSUE TITLE
The head of clang 9 is broken

### ISSUE THREAD

**Issue by drowned-robots** [melpon/wandbox#265]
Today, 24 apr, the head of clang 9.0 was broken. Yesterday was fine.
C++2a,
compiler flags: -stdlib=libc++
Try to compile code and get error:
/usr/bin/ld: cannot find /root/tmp/clang-head/build/lib/libc++.so.1
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by melpon** [comment]
Today is fine

**Comment by drowned-robots** [comment]
Yes, today is fine. But you didn't fix anything?)

**Comment by melpon** [comment]
No, I didn't fix anything. I think that was fixed by the daily build on Wandbox.
