### ISSUE TITLE
Can't execute source codes in Go 1.12+

### ISSUE THREAD

**Issue by cia-rana** [melpon/wandbox#266]
wandbox can't execute source codes with Go1.12+, because environment variable `GO111MODULE` is set to `on` in Go1.12+ by default and they require the executors to have a go module file locally. Furthermore, in that situation, Go1.12+ download automatically missing dependency packages. So when wandbox executes source codes with Go1.12+, the environment variable needs to be set to `off`.

https://tip.golang.org/doc/go1.12#modules

### Error log
- Language: go HEAD devel +2177bfb
```
Start
go: cannot find main module; see 'go help modules'
1
Finish
```

**Comment by melpon** [comment]
It is fixed with `GO111MODULE=off` environment. Thank you for reporting and advice!
