### ISSUE TITLE
"Runtime options" seems not to work properly

### ISSUE THREAD

**Issue by mmatrosov** [melpon/wandbox#270]
Hello. I'm trying to specify an environment variable for the run (actually, I'm trying to run [UBSan with symbolization](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#stack-traces-and-report-symbolization), which requires to set `UBSAN_OPTIONS` and `PATH` env variables). To test this out, I wrote a minimal program to echo a variable with `std::system`, which I set in "Runtime Options" box: https://wandbox.org/permlink/DLnXf6SQD25AQulb

But it prints empty string :( Is this is a bug? Or am I doing it wrong?

**Comment by melpon** [comment]
When runtime options are specified with `MYVAR=123`, Wandbox is running with `./a.out MYVAR=123`.
So it is passed as arguments: https://wandbox.org/permlink/qtiPOUa0kVADKAWF

**Comment by mmatrosov** [comment]
Damn, this should have been obvious. Is there a way to specify an environment variable for the run?

**Comment by melpon** [comment]
There are several ways:
- Call system function recursively: https://wandbox.org/permlink/kYcWx1son06CLEDi
- Using bash: https://wandbox.org/permlink/sI9r0p8JoxmorZzT

**Comment by mmatrosov** [comment]
Awesome! Thank you very much!
