### ISSUE TITLE
Output not displayed before std::this_thread::sleep_for() is called

### ISSUE THREAD

**Issue by flriancu** [melpon/wandbox#271]
When running the following code, the output console displays "Start" and nothing more [1], then after 5 seconds it displays the entire output (from before and after `sleep_for`). It seems that it happens no matter what compiler I choose. All options (except the compiler) are default.

```
#include <iostream>
#include <chrono>
#include <thread>

int main()
{
    std::cout << "a\n";
    std::this_thread::sleep_for(std::chrono::seconds(5));
    std::cout << "b\n";
    
    return 0;
}
```

[1]
![image](https://user-images.githubusercontent.com/8483893/58252720-720ff100-7d6f-11e9-8c50-55802b735399.png)

**Comment by melpon** [comment]
Please test it at local. I think it will be occurred same problem.

You can use `flush`:

```cpp
#include <iostream>
#include <chrono>
#include <thread>

int main()
{
    std::cout << "a\n";
    std::cout.flush(); // Add this line
    std::this_thread::sleep_for(std::chrono::seconds(5));
    std::cout << "b\n";
    
    return 0;
}```

**Comment by fetus-hina** [comment]
FYI:
`g++` 4.8.5 (on CentOS 7 on my Linux box; it's very old!) with `-std=c++11` option puts `a` soon,  then `b` 5 seconds later.
However, I agree with melpon's comment. It needs `flush`ing like the code or
```c++
std::cout << "a\n" << std::flush;
```
or
```c++
std::cout << "a" << std::endl;
```

**Comment by flriancu** [comment]
@melpon local testing with g++ 7.3.0 and `-std=c++17` prints output before `sleep_for`. Testing on wandbox with the same settings does not print the output.
@fetus-hina 
Flushing the output buffer solves the problem on wandbox, thank you!

**Comment by melpon** [comment]
@flriancu So it is not Wandbox issue.

**Comment by melpon** [comment]
It seems that buffering does not work well on the console. However, you can run into problems by calling `./a.out > foo` while doing` touch foo && tail -f foo`.
