### ISSUE TITLE
Expand button doesn't resize editor or output window

### ISSUE THREAD

**Issue by matkatmusic** [melpon/wandbox#276]
see: https://wandbox.org/permlink/MFmoz2qrYr4s7Men and toggle the 'expand' button on the right.

using Chrome 74.0.3729.169 (Official Build) (64-bit) on OS X.

**Comment by melpon** [comment]
I do not need it. If you want to it feature, please send PR.

**Comment by melpon** [comment]
Fixed by reverting.

**Comment by matkatmusic** [comment]
@melpon I have no idea what broke between when you removed the expand the first time and when you removed it this time.  It is a very useful feature.  How are you using Wandbox such that you don't need to see more than 20 lines of code at a time?  @fetus-hina offered some suggestions on what caused the expand button to not work this time.  Care to take a look at their suggestions?
