### ISSUE TITLE
[FR] Can the Text Editor auto-expand? 

### ISSUE THREAD

**Issue by matkatmusic** [melpon/wandbox#278]
Right now it only shows 23 lines max.

**Comment by melpon** [comment]
By design.

**Comment by matkatmusic** [comment]
No other online IDE tool has this limitation.  Coliru, repl.it, godbolt,
cppinsights, hastebin, pastebin, you name it, they don't have this viewable
lines limitation in their text editor.  Why is this limitation "by design"?
