### ISSUE TITLE
Wandbox does not seem to compile code anymore when there is accents

### ISSUE THREAD

**Issue by XaF** [melpon/wandbox#283]
Example of the issue: https://wandbox.org/permlink/6JJvA7tFXXuOtZVO
Solved by removing accents in the header: https://wandbox.org/permlink/GXMI7zO60O4omd6f

This seems like a regression introduced in some changes. Not sure exactly about the last time it worked, but it was working previously!

**Comment by melpon** [comment]
It seems same code. What is changed?

**Comment by XaF** [comment]
The one not working anymore has the accents that have been there since 4 years ago (my first name at the beginning of the header comment and in "École Polytechnique de Montréal" at the end of that same header comment.

The code that now works has those accents removed and replaced by the un accented characters. But as I said, the accents were not an issue before!

**Comment by melpon** [comment]
I understood and confirmed the issue. I'm trying to fix it now.

**Comment by melpon** [comment]
Fixed. Thank you for reporting.
