### ISSUE TITLE
Permlinks do not load in Microsoft Edge browser

### ISSUE THREAD

**Issue by DanielLangr** [melpon/wandbox#285]
Wandbox permlinks does not load for me in Microsoft Edge. I even tried the anonymous (InPrivate) window to eliminate the effect of cookies. Example: https://wandbox.org/permlink/4KuSprBEccX2IKOp. In Edge, the Wandbox home page is loaded (empty contents without any code and selected language).

**Comment by fetus-hina** [comment]
It looks now works with the polyfill library on Edge and IE 11.

**Comment by fetus-hina** [comment]
@DanielLangr Could you mark close this issue if you confirmed the fix?
Or let us know it hasn't been fixed yet.
