### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by Bolpat** [melpon/wandbox#292]
Why is there no button on the web interface for creating a permalink? (Or am I missing it the whole time?)

**Comment by melpon** [comment]
Run ボタンをクリックしてください。そうすれば Share ボタンが現れます。
<img width="269" alt="スクリーンショット 2020-02-04 11 17 19" src="https://user-images.githubusercontent.com/816539/73707849-f8266900-473f-11ea-8db5-280725497748.png">
