### ISSUE TITLE
Website seems down right now

### ISSUE THREAD

**Issue by easyaspi314** [melpon/wandbox#297]
https://wandbox.org seems to be timing out with a 504 error currently.
![Screenshot_20200411-123140](https://user-images.githubusercontent.com/6258309/79049368-439e3d00-7bf1-11ea-96a1-8139410afd75.png)

**Comment by melpon** [comment]
ひとまず復旧しました。原因はこれから調べます。

**Comment by easyaspi314** [comment]
ありがとう。
