### ISSUE TITLE
uidを実行ごとに分離する

### ISSUE THREAD

**Issue by kikairoya** [melpon/wandbox#303]
制約事項の確認:

- 分離はcattlegridで行う
 cattlegridにcap_setuid,cap_setgid,cap_chownを追加
- たまたま同じuidを同時に使う可能性があるが、それはあきらめる
 uidは32bit使えるから被る率は低い
- chown -Rで一度トラバースするのでI/Oは増える
 postされたコードを保存するcattleshedはwandbox:wandboxなので仕方ない
- /tmp/wandboxXXXXXX以下をwandbox:wandboxで読む・消すことはできなくなる
 この制約が厳しければgidはwandboxのまま分離しなくてもよいかも

**Comment by melpon** [comment]
権限に関しては、大体 root でやってるので問題ないと思います
