### ISSUE TITLE
Incomplete API return

### ISSUE THREAD

**Issue by Headline** [melpon/wandbox#307]
Hello!

Within the last few hours I am no longer receiving `status`, `program_message` or `compiler_message` from the API. I'm receiving a valid URL, but all compilations seem impacted.

**Comment by Headline** [comment]
It seems to have been resolved, still interesting how this happened, though. Something you might want to investigate so I'll leave this open for now

**Comment by melpon** [comment]
Fixed. Thank you for reporting!
