### ISSUE TITLE
Link broken Boost.SML and Boost.DI in README.md

### ISSUE THREAD

**Issue by tt4g** [melpon/wandbox#308]
The links to the Boost.SML (https://boost-experimental.github.io/sml/examples/index.html) and Boost.DI (https://boost-experimental.github.io/di/examples/index.html) documents are broken.

* Boost.SML

  Should fix link url to https://boost-experimental.github.io/sml/ or https://boost-experimental.github.io/sml/examples.html.

* Boost.DI

  Should fix link url to https://boost-experimental.github.io/di/ or https://boost-experimental.github.io/di/examples.html

**Comment by melpon** [comment]
Thanks!
