### ISSUE TITLE
Runtime options が機能しなくなっている

### ISSUE THREAD

**Issue by srz-zumix** [melpon/wandbox#312]
https://wandbox.org/permlink/OFTwPXnJt1cyP3rt
以前は Runtime options で起動引数を指定できていた気がするのですが、
現在機能してないようです。

**Comment by melpon** [comment]
https://github.com/melpon/wandbox/blob/5f7c274d90af512eb8204877a8265eba47f5a7ff/kennel2/src/kennel.cpp#L567 なんかこれっぽい…。
ありがとうございます。直します。

**Comment by melpon** [comment]
直りました。報告ありがとうございます！

**Comment by srz-zumix** [comment]
修正確認しました。
ありがとうございます！
