### ISSUE TITLE
Firefox でコピペすると改行が消える

### ISSUE THREAD

**Issue by melpon** [melpon/wandbox#44]
https://twitter.com/bolero_MURAKAMI/status/364538493596213249

**Comment by mikecat** [comment]
http://8cmp.blog.fc2.com/blog-entry-47.html
なぜかFirefoxで`white-space: pre;`を使うとコピペ時に改行が反映されないようなので
(`white-space: pre-wrap;`でも同様?)、`<pre>`タグで囲むようにすると改善するかもしれません。

**Comment by melpon** [comment]
`<pre>`タグにしたらいけました！ありがとうございます！
