### ISSUE TITLE
コンパイラのビルドを別サーバに移す

### ISSUE THREAD

**Issue by melpon** [melpon/wandbox#71]

**Comment by melpon** [comment]
## 現状の課題、制約、要望など
- 組み合わせ爆発が起きてて、手で追加するのは無理がある
- 特定の組み合わせに対してはパッチが必要になっている
- ビルドの順序を考慮しなければならない
- Boostとかのライブラリを追加すると、C++系コンパイラ（の設定）全てに更新が入る
- UI上でのコンパイラの並び順を制御する必要がある

## debranch側の対応
- パッケージリスト(series)を手動+自動でビルド順序を制御できるようにする
- specファイルとライブラリの組み合わせを、テンプレート+一部手動(パッチとか)で作れるようにする

## cattleshed側の対応
- 各コンパイラ用のconfを自動生成し、GitHubなどで管理
- 自動生成する元となるソースには、特定の組み合わせに対する除外機能を入れる

## その他
- 実験のための環境あるといいよね

## メモ
```
- コンパイラ追加: そのコンパイラのboostパッケージが増える
- boost追加: そのboostのコンパイラパッケージが増える

- パッチ設定
- 組み合わせの排除

- パッケージリスト(series)
  - 手動+自動
- 対応するspecファイル
  - spec手動+一部手動+自動
  - パッチ(手動のみ) 

boost-1.58:
  - sources.listにソースを書く
  - MD5があれば書く。無ければ手動でDLしてきて調べる
  - パッケージリストの順序を制御するのを書く
  - specに手動でやる必要があるなら書く
  - パッチが必要なら書く

boost-1.58:
  url: "hoge",
  md5: "fuga",
  spec-template: "aaa.spec.tmpl",
  gen-spec-sh: "gen-boost-spec.sh",
  spec: "foo.patch",

gcc-5.0.0:
  - sourcest.listにソースを書く
  - MD5なりがあれば書く。無ければ手動でDLしてきて調べる
  - パッケージリストの順序を制御するのを書く
  - specに手動でやる必要があるなら書く
  - パッチが必要なら書く

newlib-1.0:
  - spec新規（orテンプレート）で書く
  - テンプレートならgen-newlib-spec書く
  - sources.listに書く
  - 以下同文

  - confファイル
  - 自動生成するしか
    - 特別扱いがむずい
```

**Comment by melpon** [comment]
@kikairoya 
Webhookによって、Wandbox側からkennelやcattleshedのビルドを行なってapt-get installしたい。
なので、ssh経由で1コマンドでビルド＆パッケージ化できる何かを用意して欲しい。

**Comment by melpon** [comment]
Webhookで動くようにしたら、ちょっとずつ処理系を新しいのに置き換えていく

**Comment by kikairoya** [comment]
$ ./build-all-packages --inc={ここに,パッケージ名を,並べる} -c -r -k -a
で欲しいパッケージだけを強制的に更新できるようにした
aptはもうしょうしょうおまちください
